apiVersion: apps/v1
kind: Deployment
metadata:
  name: insuranceapp-deploy
  labels:
    app: insuranceapp-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: insuranceapp-app
  template:
    metadata:
      labels:
        app: insuranceapp-app
    spec:
      containers:
      - name: insuranceapp-container
        image: dhakshana1197/insuranceapp-app
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: insuranceapp-np-service
  labels:
    app: insuranceapp-app
spec:
  selector:
    app: insuranceapp-app

  type: NodePort
  ports:
  - nodePort: 31002    
    port: 8081
    targetPort: 8081
